// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as
  | string
  | undefined;

if (!SUPABASE_URL?.trim() || !SUPABASE_PUBLISHABLE_KEY?.trim()) {
  throw new Error(
    [
      "Supabase 클라이언트 설정이 없습니다.",
      "Vercel → Settings → Environment Variables 에 URL·anon 키를 넣고 재배포하세요.",
      "가능한 이름: VITE_SUPABASE_URL 또는 SUPABASE_URL,",
      "VITE_SUPABASE_PUBLISHABLE_KEY 또는 SUPABASE_PUBLISHABLE_KEY 또는 SUPABASE_ANON_KEY.",
      "service_role 키는 클라이언트에 넣지 마세요.",
    ].join(" ")
  );
}

const trimmedUrl = SUPABASE_URL.trim();
let supabaseHost = "";
try {
  const u = new URL(trimmedUrl);
  if (u.protocol !== "https:") {
    throw new Error("https 가 아닙니다.");
  }
  supabaseHost = u.hostname.toLowerCase();
} catch {
  throw new Error(
    "Supabase URL 형식이 잘못되었습니다. 대시보드 → Settings → API 의 Project URL 전체를 복사하세요. (예: https://abcdefghijklmnop.supabase.co)"
  );
}

if (!supabaseHost.endsWith(".supabase.co")) {
  throw new Error(
    `Supabase URL 호스트가 supabase.co 가 아닙니다: ${supabaseHost}. 대시보드에 표시된 URL을 그대로 쓰세요.`
  );
}

const projectRef = supabaseHost.replace(/\.supabase\.co$/, "");
const placeholderRefs = /^(xxxx|xxx|example|placeholder|your-project|my-project|project-ref)$/i;
if (!projectRef || placeholderRefs.test(projectRef)) {
  throw new Error(
    "Supabase URL 에 실제 프로젝트 주소가 아니라 예시(xxxx 등)가 들어간 것 같습니다. Settings → API 의 Project URL 을 다시 넣고 재배포하세요."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(trimmedUrl, SUPABASE_PUBLISHABLE_KEY.trim(), {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});